### ISSUE TITLE
broken build?

### ISSUE THREAD

**Issue by The0ldM0nk** [hypeapps/episodie#13]
Hi,
I really like the project structure but the master branch appears to be broken.
Also, add-to-watched-feature branch is broken as well though it looks to be more newer than master.

Am I missing something here?

**Comment by hypeapps** [comment]
Hi @The0ldM0nk 
Yes, your'e right that master was broken. I just commited missing classes. TravisCI build check passes well. Pull master branch and everything should be fine. Let me know if still there's problem with build.

**Comment by The0ldM0nk** [comment]
@hypeapps works fine now. 
Cheers!
Will keep a close eye on this project :)

**Comment by hypeapps** [comment]
@The0ldM0nk Yes, feel free to make PRs.
