### ISSUE TITLE
Not working version 1.0.2

### ISSUE THREAD

**Issue by anjannath** [hypeapps/episodie#33]
I installed it today, and it just shows a toast message saying "something went wrong", and the disconnected icon. I have internet access and can browse the tvmaze.com site

**Comment by hypeapps** [comment]
Thank you for the report. Can you check now?

**Comment by anjannath** [comment]
Thanks, its working now, what was the issue, tvmaze api? <strike>The one released in f-droid still has the issue :(</strike>

**Comment by hypeapps** [comment]
No. My free server sometimes shutdown all services and then I have to
restart :)

**Comment by shashankmc** [comment]
Hello! Facing this issue post installation as well. Its saying "something went wrong".

**Comment by hypeapps** [comment]
@shashankmc Now it's working. I have a problem with server where my API is hosted.

**Comment by shashankmc** [comment]
Oh okay, just checked and its working. Is there anything, from my side, that can be done to help?

**Comment by hypeapps** [comment]
@shashankmc Thank you! If you know a free server hosting (can be shared hosting) where I can host tomcat server with minmum 512mb ram then let me know :)

**Comment by shashankmc** [comment]
I will check with people I know but have you looked at 2freehosting.com ; I honestly haven't looked into it detail but will get back on this once I get sometime! :)

**Comment by marlid91** [comment]
Same problem for me
